In [5]:
import numpy as np



In [6]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.shape

(3,)

In [9]:
arr2 = np.array([[1,2],[3,4]])
print(arr2)

[[1 2]
 [3 4]]


In [10]:
arr2.shape

(2, 2)

In [11]:
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3)
print(arr3.shape)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [12]:
array = np.array([1,2,3,])
print(array*2)

[2 4 6]


In [13]:
py_list = [1,2,3]
print(py_list*2)

[1, 2, 3, 1, 2, 3]
